# This file was generated by GoReleaser. DO NOT EDIT.
cask "kommit" do
  desc ""
  homepage "https://github.com/madflow/kommit"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kommit"

  on_macos do
    on_intel do
      url "https://github.com/madflow/kommit/releases/download/v0.5.0/kommit_Darwin_x86_64.tar.gz"
      sha256 "8598ac6d5c75e22176cf0beaf51b896efcd0685cbd9e89cf9694a91642860e90"
    end
    on_arm do
      url "https://github.com/madflow/kommit/releases/download/v0.5.0/kommit_Darwin_arm64.tar.gz"
      sha256 "19e152d9a0e32f99df1bb1c8432f6b0af01cbca392210f0811c7583ca13f1086"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/madflow/kommit/releases/download/v0.5.0/kommit_Linux_x86_64.tar.gz"
      sha256 "43afe8c45387f0c2497d8217cf32e19b7512cc4e067ed597aa6e4210cd5ed666"
    end
    on_arm do
      url "https://github.com/madflow/kommit/releases/download/v0.5.0/kommit_Linux_arm64.tar.gz"
      sha256 "ec5a82c98566f5db73345ccb6391365e26d20c8b97100a0cf6dceed4443ad582"
    end
  end

  conflicts_with formula: [
      "kommit",
    ]

  # No zap stanza required
end
