# This file was generated by GoReleaser. DO NOT EDIT.
cask "kommit" do
  desc ""
  homepage "https://github.com/madflow/kommit"
  version "0.5.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kommit"

  on_macos do
    on_intel do
      url "https://github.com/madflow/kommit/releases/download/v0.5.2/kommit_Darwin_x86_64.tar.gz"
      sha256 "67efd0c641656afe2be03d5f0340848447f2088c335a17d9520910a31bfd5685"
    end
    on_arm do
      url "https://github.com/madflow/kommit/releases/download/v0.5.2/kommit_Darwin_arm64.tar.gz"
      sha256 "c49e3ce631ac1bf48a55836c37e2b601fc1d36a5437712a0c3376520341b0ce5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/madflow/kommit/releases/download/v0.5.2/kommit_Linux_x86_64.tar.gz"
      sha256 "f928fed77dbd6300cea49e175443142ddfb7dc16233b26f891c462da71c030a1"
    end
    on_arm do
      url "https://github.com/madflow/kommit/releases/download/v0.5.2/kommit_Linux_arm64.tar.gz"
      sha256 "3a9ff55090b798c79bf05601408d84b55d40bbec54f24876489a03309f70f7b3"
    end
  end

  conflicts_with formula: [
      "kommit",
    ]

  # No zap stanza required
end
