# This file was generated by GoReleaser. DO NOT EDIT.
cask "kommit" do
  desc ""
  homepage "https://github.com/madflow/kommit"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kommit"

  on_macos do
    on_intel do
      url "https://github.com/madflow/kommit/releases/download/v0.0.2/kommit_Darwin_x86_64.tar.gz"
      sha256 "da2b9c373164d4c5719d102fead7a9e46fb14aa47026944cb0cbaeb2fe7bf055"
    end
    on_arm do
      url "https://github.com/madflow/kommit/releases/download/v0.0.2/kommit_Darwin_arm64.tar.gz"
      sha256 "6578267ff168192fb24e2cd8feefc7352b8a1d56033d828c435a4cd1d9ed9ba8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/madflow/kommit/releases/download/v0.0.2/kommit_Linux_x86_64.tar.gz"
      sha256 "c37463f65c99c5e247fca415ad0e72d7a46a8ed7ba9915e14385008cc1a19e28"
    end
    on_arm do
      url "https://github.com/madflow/kommit/releases/download/v0.0.2/kommit_Linux_arm64.tar.gz"
      sha256 "c1bcf35f26eeefd1c33a53a755804d3dd01cd9d3f6de7bcd9cad37d8ce32d925"
    end
  end

  conflicts_with formula: [
      "kommit",
    ]

  # No zap stanza required
end
